name: booking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  http: ^1.5.0
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  flutter_svg: ^2.2.0
  google_fonts: ^6.3.0
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.11.0
  build_runner: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - .env

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
